http_server:
  host: "localhost"
  port: 8080

servers:
  # specify servers that balancer will connect to
  - url: "localhost:8081"
    weight: 1 # represents the weight of the server (optional. default: 1)
  - url: "localhost:8082"
    weight: 2
  - url: "localhost:8083"
    weight: 3
  # - url: "localhost:8084"
  #   weight: 4
  # - url: "localhost:8085"
  #   weight: 5
  # - url: "localhost:8086"
  #   weight: 1
  # - url: "localhost:8087"
  #   weight: 1
  # - url: "localhost:8088"
  #   weight: 1
  # - url: "localhost:8089"
  #   weight: 1
  # - url: "localhost:8090"
  #   weight: 1

balancing_alg: "least_connections" # choose balancing algorithm (algs: round_robin, weighted_round_robin, least_connections, hash, random)

health_check:
  interval: 5s
  timeout: 2s

logging:
  level: "info"
  path: "logs/balancer.log"

servers_outage:    # Используется для имитации сбоя работы серверов.
  after: 10        # Время в секундах (целое число), через которое будет происходить сбой. Установить -1 для отключения имитации.
  multiplier: 1.2 # Коэффициент увеличения времени сбоя. Увеличивается каждый раз после предыдущего сбоя.