http_server:
  host: "localhost"
  port: 8080

servers:
  - url: "localhost:8081"
    weight: 1
  - url: "localhost:8082"
    weight: 2
  - url: "localhost:8083"
    weight: 3

balancing_alg: "weighted_round_robin"

health_check:
  interval: 5s
  timeout: 2s

logging:
  level: "debug"
  path: "logs/test2.log"

servers_outage:
  after: 10