http_server:
  host: "localhost"
  port: 8080

https_server:
  host: "localhost"
  port: 8443
  cert_file: "server.crt"
  key_file: "server.key"


servers:
  - url: "localhost:8081"
    weight: 1
  - url: "localhost:8082"
    weight: 2
  - url: "localhost:8083"
    weight: 2

balancing_alg: "weighted_round_robin"

health_check:
  interval: 5s
  timeout: 2s

logging:
  rewrite: true 
  level: "info" 
  path: "logs/" 
  file: "server.log" 

servers_outage:    
  after: 0   
  multiplier: 1.75